<script>
var a = 10;

console.log(a) // 10

// try is used for the statement which can provides error 

try{
    var b = 20 ;
    console.log(bb)

}

// catch is used to handle the error 

catch(e){
    console.error("error occures is ....",e.message);
}
// finaly is used to run the statement if error occures or not occures..

finally{
    console.log("Program Ends Successfully...");
}


var c = 30;
console.log(c)
</script>